[package]
name = "pytextopia"
version = "0.1.0"
edition = "2021"

[lib]
name = "pytextopia"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
textopia = { path = "../../"}

